#!/bin/bash
#
# Configure bttv card for sidux
#
# License: GPL
#
# Author: Fabian Franz <knx-xawtv@fabian-franz.de>
#
# Spanish translation by Sergio González, <sergio.gonzalez@hispalinux.es>

# override tool behaviour through distro-defaults
#
#--------------------------------------------------------------
PATH="/bin:/sbin:/usr/bin:/usr/sbin"
export PATH

# we need gettext (is loaded in ssft.sh or cloned...)
if [ -f /usr/bin/gettext.sh ]; then
        . /usr/bin/gettext.sh || exit 1
else
        exit 1
fi

TEXTDOMAIN="configure_bttv"
export TEXTDOMAIN
TEXTDOMAINDIR=/usr/share/locale
export TEXTDOMAINDIR


FLL_DISTRO_MODE="installed"
[ -r /etc/default/distro ] && source /etc/default/distro

clean_exit () {
	[ -f "$TMP" ] && rm -f "$TMP"
}

CARDLIST_BTTV="/usr/share/configure-bttv/CARDLIST.bttv.gz"
CARDLIST_TUNER="/usr/share/configure-bttv/CARDLIST.tuner.gz"

trap clean_exit EXIT

# determine system status
SSFTSH="$(which ssft.sh)"       || SSFTSH="/usr/bin/ssft.sh"

# initialize ssft
#[ -n "$DISPLAY" ] && [ -x /usr/bin/kdialog ] && SSFT_FRONTEND="kdialog"
. "$SSFTSH"
[ -n "$SSFT_FRONTEND" ] ||  SSFT_FRONTEND="$(ssft_choose_frontend)"

MAX=3


NCARDLIST=$(gzip -dc $CARDLIST_BTTV | sed -e "s|'|\"|g")	# ' in the list won't work with ssft

IFS='
'
STEP=1
ssft_select_single \
	"$(eval_gettext "Initial setup of TV-card (Step \${STEP}/\${MAX})")" \
	"$(gettext "Please select your TV card from the list.")" $NCARDLIST   || exit 1
unset IFS

CARD="$(echo $SSFT_RESULT| awk '{print $1}')"

NTUNERLIST=$(gzip -dc $CARDLIST_TUNER |awk -F "=" '/tuner=/{print $2}') 

IFS='
'
STEP=2
ssft_select_single \
	"$(eval_gettext "Initial setup of TV-card (Step \${STEP}/\${MAX})")" \
	"$(gettext "Please select the type of your tuner.")" $NTUNERLIST  || exit 1
unset IFS

TUNER=$(echo $SSFT_RESULT | awk '{print $1}')

STEP=3
ssft_display_message \
	"$(eval_gettext "Initial setup of TV-card (Step \${STEP}/\${MAX})")" \
	"$(gettext "The script will now try to load the necessary modules with this parameters . Then it'll start xawtv.")"

if [ -x "$(which su-to-root)" ]; then
	su-to-root -c "/sbin/rmmod -r bttv ; \
		/sbin/rmmod -r tuner; \
		/sbin/modprobe bttv card=\"$CARD\" tuner=\"$TUNER\"; \
		rm -f /etc/modprobe.d/bttv \
		echo \"options bttv card=$CARD tuner=$TUNER\" > /etc/modprobe.d/bttv "
	[ ! "$FLL_DISTRO_MODE" = "live" ] su-to-root -c update-modules -f &>/dev/null
else
	ssft_display_error \
		"$(eval_gettext "Error")" \
		"$(gettext ""ERROR: $0 needs root capabilities, please start it as root")"
	exit 1
fi
exec xawtv.wrapper

