#!/bin/bash
#
# Pre-Configure xawtv for sidux
#
# License: GPL
#
# Based on initial work by Kai Lahmann <kl@3dots.de>
#
# Patches and Debian package by Fabian Franz <knx-xawtv@fabian-franz.de>
#
# Spanish translation by Sergio González, <sergio.gonzalez@hispalinux.es>
#
# 
#--------------------------------------------------------------
PATH="/bin:/sbin:/usr/bin:/usr/sbin"
export PATH

# we need gettext (is loaded in ssft.sh or cloned...)
if [ -f /usr/bin/gettext.sh ]; then
	. /usr/bin/gettext.sh || exit 1
else
	exit 1
fi

TEXTDOMAIN="configure_xawtv"
export TEXTDOMAIN
TEXTDOMAINDIR=/usr/share/locale
export TEXTDOMAINDIR


clean_exit() {
  [ -f "$TMP" ] && rm -f "$TMP"
}

trap clean_exit EXIT

TMP="$(mktemp -p /tmp/ configure_xawtv-XXXXXXXXXX)"

if [ "$1" = "scantv" ]; then
	shift
	TMPFILE="$1"
	shift
	scantv "$@" > "$TMP" || exit 1
	cat "$TMP" > "$TMPFILE"
	exit 0 
fi


MAX=4

case "$LANG" in
   de*|at*|ch*)
     BT="xawtv-Konfiguration"
     T1="Einrichtung von xawtv (Schritt 0/$MAX)"
     MESSAGE1="Bitte wählen Sie ihre TV-Norm aus."
     MESSAGE2="Bitte wählen Sie eine Frequenztabelle aus."
     MESSAGE3="Das Skript wird jetzt versuchen alle verfügbaren Fernsehsender zu finden. Dies kann eine Weile dauern. Bitte haben Sie Geduld."
     MESSAGE4="Die Installation ist abgeschlossen. xawtv wird nun gestartet. Fröhliches Fernsehgucken!"
     MESSAGE5="Die Installation wurde abgebrochen. Wollen Sie xawtv trotzdem starten?\n\n(Um den Wrapper permanent zu deaktivieren legen Sie bitte eine Datei ~/.xawtv an oder lassen Sie dieses Skript einmal vollständig durchlaufen.)"
     ;;
   es*)
     BT="Configuración de xawtv"
     T1="Configuración inicial para xawtv (Paso 0/$MAX)"
     MESSAGE1="Por favor, seleccione su norma de TV"
     MESSAGE2="Por favor, seleccione una tabla de frecuencias."
     MESSAGE3="El script intentará buscar nuevos canales de televisión. Esto puede tomar un momento. Por favor, sea paciente." 
     MESSAGE4="La instalación se ha completado. xawtv se ejecutará ahora. ¡Feliz visionado!"
    ;;
   *)
     BT="xawtv-Configuration"
     T1="Initial setup of xawtv (Step 0/$MAX)"
     MESSAGE1="Please select your TV norm."
     MESSAGE2="Please select a frequency table."
     MESSAGE3="The script will now try to find all available TV channels. This can take a while. Please be patient." 
     MESSAGE4="The Installation is complete. xawtv will now be started. Happy watching!"
     MESSAGE5="The Installation was aborted. Do you want to start xawtv anyway ?\n\n(To deactivate the wrapper permanently create a ~/.xawtv or let this script finish normally.)"
    ;;
esac

exit_proc() 
{
	ssft_yesno "${T1/0/1}"  "$(gettext "The Installation was aborted. Do you want to start xawtv anyway ?\n\n(To deactivate the wrapper permanently create a ~/.xawtv or let this script finish normally.)")"
	exit $?
}


# determine system status
SSFTSH="$(which ssft.sh)"	|| SSFTSH="/usr/bin/ssft.sh"
ZENITYSH="$(which zenity)"	|| ZENITYSH="/usr/bin/zenity"
DIALOGSH="$(which dialog)"	|| DIALOGSH="/usr/bin/dialog"

# initialize ssft
#[ -n "$DISPLAY" ] && [ -x /usr/bin/kdialog ] && SSFT_FRONTEND="kdialog"
. "$SSFTSH"
[ -n "$SSFT_FRONTEND" ] ||  SSFT_FRONTEND="$(ssft_choose_frontend)"


NORMLIST="PAL NTSC SECAM PAL-NC PAL-M NTSC-JP"

ssft_select_single "${T1/0/1}" "$(gettext "Please select your TV-norm")" $NORMLIST exit  || exit_proc
[ "$SSFT_RESULT" = "exit" ] && exit_proc
NORM="$SSFT_RESULT"

TABLELIST="europe-west europe-east us-bcast us-cable us-cable-hrc japan-bcast japan-cable italy newzealand australia ireland france china-bcast southafrica argentina australia-optus russia"
ssft_select_single "${T1/0/2}" "$(gettext "Please select a frequency table.")" $TABLELIST exit || exit_proc
[ "$SSFT_RESULT" = "exit" ] && exit_proc
TABLE="$SSFT_RESULT"

ssft_display_message  "${T1/0/3}" "$(gettext "The script will now try to find all available TV channels. This can take a while. Please be patient.")" 


if [ -n "$DISPLAY" ]; then
	x-terminal-emulator -e "$0" scantv "$TMP" -n "$NORM" -f "$TABLE" -C /dev/vbi0
else
	"$0" scantv "$TMP" -n "$NORM" -f "$TABLE" -C /dev/vbi0
fi

[ ! -r "$TMP" ] && exit_proc

mv -f "$TMP" ~/.xawtv

ssft_display_message  "${T1/0/4}" "$(gettext "The Installation is complete. xawtv will now be started. Happy watching!")"

exit 0

