#!/bin/bash
#
# Pre-Configure xawtv for sidux
#
# License: GPL
#
# Based on initial work by Kai Lahmann <kl@3dots.de>
#
# Patches and Debian package by Fabian Franz <knx-xawtv@fabian-franz.de>
#
# Spanish translation by Sergio González, <sergio.gonzalez@hispalinux.es>
#
# 
#--------------------------------------------------------------
PATH="/bin:/sbin:/usr/bin:/usr/sbin"
export PATH

# we need gettext (is loaded in ssft.sh or cloned...)
if [ -f /usr/bin/gettext.sh ]; then
	. /usr/bin/gettext.sh || exit 1
else
	exit 1
fi

TEXTDOMAIN="configure_xawtv"
export TEXTDOMAIN
TEXTDOMAINDIR=/usr/share/locale
export TEXTDOMAINDIR


clean_exit() {
  [ -f "$TMP" ] && rm -f "$TMP"
}

trap clean_exit EXIT

TMP="$(mktemp -p /tmp/ configure_xawtv-XXXXXXXXXX)"

if [ "$1" = "scantv" ]; then
	shift
	TMPFILE="$1"
	shift
	scantv "$@" > "$TMP" || exit 1
	cat "$TMP" > "$TMPFILE"
	exit 0 
fi


MAX=4

exit_proc() 
{
	STEP=1
	ssft_yesno \
		"$(eval_gettext "Initial setup of xawtv (Step \${STEP}/\${MAX})")" \
		"$(gettext "The Installation was aborted. Do you want to start xawtv anyway ?\n\n(To deactivate the wrapper permanently create a ~/.xawtv or let this script finish normally.)")"
	exit $?
}


# determine system status
SSFTSH="$(which ssft.sh)"	|| SSFTSH="/usr/bin/ssft.sh"

# initialize ssft
#[ -n "$DISPLAY" ] && [ -x /usr/bin/kdialog ] && SSFT_FRONTEND="kdialog"
. "$SSFTSH"
[ -n "$SSFT_FRONTEND" ] ||  SSFT_FRONTEND="$(ssft_choose_frontend)"


NORMLIST="PAL NTSC SECAM PAL-NC PAL-M NTSC-JP"

STEP=1
ssft_select_single \
	"$(eval_gettext "Initial setup of xawtv (Step \${STEP}/\${MAX})")" \
	"$(gettext "Please select your TV-norm")" $NORMLIST exit  || exit_proc
[ "$SSFT_RESULT" = "exit" ] && exit_proc
NORM="$SSFT_RESULT"

TABLELIST="europe-west europe-east us-bcast us-cable us-cable-hrc japan-bcast japan-cable italy newzealand australia ireland france china-bcast southafrica argentina australia-optus russia"
STEP=2
ssft_select_single \
	"$(eval_gettext "Initial setup of xawtv (Step \${STEP}/\${MAX})")" \
	"$(gettext "Please select a frequency table.")" $TABLELIST exit || exit_proc
[ "$SSFT_RESULT" = "exit" ] && exit_proc
TABLE="$SSFT_RESULT"

STEP=3
ssft_display_message  \
	"$(eval_gettext "Initial setup of xawtv (Step \${STEP}/\${MAX})")" \
	"$(gettext "The script will now try to find all available TV channels. This can take a while. Please be patient.")" 


if [ -n "$DISPLAY" ]; then
	x-terminal-emulator -e "$0" scantv "$TMP" -n "$NORM" -f "$TABLE" -C /dev/vbi0
else
	"$0" scantv "$TMP" -n "$NORM" -f "$TABLE" -C /dev/vbi0
fi

[ ! -r "$TMP" ] && exit_proc

mv -f "$TMP" ~/.xawtv

STEP=4
ssft_display_message  \
	"$(eval_gettext "Initial setup of xawtv (Step \${STEP}/\${MAX})")" \
	"$(gettext "The Installation is complete. xawtv will now be started. Happy watching!")"

exit 0

